### ISSUE TITLE
Help with Docker with Netboot

### ISSUE THREAD

**Issue by philcebutv** [macadmins/netboot-httpd#1]
How do I ran this on OSX? I have mac mini lying around with snow leopard on it and would like to use it as a netboot/netinstall server where I can host OSX images for restoring on bunch of iMacs

There was this package that I saw that you can download which can port or ran docker on osx. Not sure if it would support snow leopard.

Can you help me with or advise?

Basically my goal was to ran netboot/netinstall to restore different mac os x images without running an OSX server. Most probably we re-image at a maximum of 5 imacs on which I think the mac mini can handle well.

**Comment by nmcspadden** [comment]
Docker will only work on Mac OS X 10.11 or above, so you will need to upgrade first:
https://docs.docker.com/docker-for-mac/install/#what-to-know-before-you-install

Secondly, if you are upgrading to OS X 10.11+, you can also just spend the $30 in the App Store for OS X Server.app which will give you NetBoot out of the box. 

If you can't spend $30, take a look at https://github.com/bruienne/bsdpy which can run on any platform with Python (Linux, OS X etc.).

**Comment by nmcspadden** [comment]
Closing as there isn't really an issue with the repo here.  I encourage you to join the [MacAdmins Slack](https://macadmins.herokuapp.com/) and talk to some people about your scenario and how you can accomplish what you'd like.

**Comment by philcebutv** [comment]
thank you for the information you've shared. 
please close this as I wasn't so sure where I want to ask question. 

This is my first time using github.
